export const   AUTH_SIGNIN = "AUTH_SUCCESS";
export const   AUTH_SIGNOUT = "AUTH_LOGOUT";
export const   CATEGORIES="ADD-CONTENT"
export const   LOAD_CATEGORIES="LOAD-CONTENT"
export const DELETE_ITEM="DELETE-CONTENT"
export const   ADDPRODUCTS="ADD-PRODUCTS"
export const   LOAD_PRODUCTS="LOAD-PRODUCTS"
export const DELETE_PRODUCTS="DELETE-PRODUCTS"
export const CART_PRODUCTS="CART-PRODUCTS"
export const REMOVE_CART_PRODUCTS="REMOVE-PRODUCTS"




